# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/jason/UData/home/soundpadlab/jason/pipeline_nonconvex

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/jason/UData/home/soundpadlab/jason/pipeline_nonconvex

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/jason/UData/home/soundpadlab/jason/pipeline_nonconvex/CMakeFiles /media/jason/UData/home/soundpadlab/jason/pipeline_nonconvex//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/jason/UData/home/soundpadlab/jason/pipeline_nonconvex/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named multi_polygon

# Build rule for target.
multi_polygon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 multi_polygon
.PHONY : multi_polygon

# fast build rule for target.
multi_polygon/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multi_polygon.dir/build.make CMakeFiles/multi_polygon.dir/build
.PHONY : multi_polygon/fast

mesh.o: mesh.cpp.o

.PHONY : mesh.o

# target to build an object file
mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multi_polygon.dir/build.make CMakeFiles/multi_polygon.dir/mesh.cpp.o
.PHONY : mesh.cpp.o

mesh.i: mesh.cpp.i

.PHONY : mesh.i

# target to preprocess a source file
mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multi_polygon.dir/build.make CMakeFiles/multi_polygon.dir/mesh.cpp.i
.PHONY : mesh.cpp.i

mesh.s: mesh.cpp.s

.PHONY : mesh.s

# target to generate assembly for a file
mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multi_polygon.dir/build.make CMakeFiles/multi_polygon.dir/mesh.cpp.s
.PHONY : mesh.cpp.s

multi_polygon.o: multi_polygon.cpp.o

.PHONY : multi_polygon.o

# target to build an object file
multi_polygon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multi_polygon.dir/build.make CMakeFiles/multi_polygon.dir/multi_polygon.cpp.o
.PHONY : multi_polygon.cpp.o

multi_polygon.i: multi_polygon.cpp.i

.PHONY : multi_polygon.i

# target to preprocess a source file
multi_polygon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multi_polygon.dir/build.make CMakeFiles/multi_polygon.dir/multi_polygon.cpp.i
.PHONY : multi_polygon.cpp.i

multi_polygon.s: multi_polygon.cpp.s

.PHONY : multi_polygon.s

# target to generate assembly for a file
multi_polygon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multi_polygon.dir/build.make CMakeFiles/multi_polygon.dir/multi_polygon.cpp.s
.PHONY : multi_polygon.cpp.s

polygon.o: polygon.cpp.o

.PHONY : polygon.o

# target to build an object file
polygon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multi_polygon.dir/build.make CMakeFiles/multi_polygon.dir/polygon.cpp.o
.PHONY : polygon.cpp.o

polygon.i: polygon.cpp.i

.PHONY : polygon.i

# target to preprocess a source file
polygon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multi_polygon.dir/build.make CMakeFiles/multi_polygon.dir/polygon.cpp.i
.PHONY : polygon.cpp.i

polygon.s: polygon.cpp.s

.PHONY : polygon.s

# target to generate assembly for a file
polygon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multi_polygon.dir/build.make CMakeFiles/multi_polygon.dir/polygon.cpp.s
.PHONY : polygon.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... multi_polygon"
	@echo "... mesh.o"
	@echo "... mesh.i"
	@echo "... mesh.s"
	@echo "... multi_polygon.o"
	@echo "... multi_polygon.i"
	@echo "... multi_polygon.s"
	@echo "... polygon.o"
	@echo "... polygon.i"
	@echo "... polygon.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

